# Function to replace repeated punctuation
def remove_punctuation_replacer(match_obj):
    """
    Replacer for REMOVE_PUNCTUATION_PATTERN.
    If group(1) exists (a repeated punctuation other than '.'), return that single punctuation.
    Otherwise (i.e., match was multiple dots), return the string '... '.
    """
    # match_obj.group(1) will be None if the match was multiple dots ('.{2,}')
    return match_obj.group(1) if match_obj.group(1) else "... "


# Remove all whitespace and replace with a single space
REMOVE_WHITESPACES_PATTERN = (r"\s+", " ")

# Replace all consecutive occurrences of the same punctuation with a single occurrence,
# except that multiple '.' are replaced with '... '
REMOVE_PUNCTUATION_PATTERN = (
    r'([!\"#$%&\'()*+,\-/:;<=>?@[\\\]^_`{|}~])\1+|\.{2,}',
    remove_punctuation_replacer
)

# dict of common contractions in english and their long form
CONTRACTIONS_DICT = \
    {"'aight": "alright",
     "ain't": "are not",
     "amn't": "am not",
     "aren't": "are not",
     "can't": "can not",
     "'cause": "because",
     "could've": "could have",
     "couldn't": "could not",
     "couldn't've": "could not have",
     "daren't": "dare not",
     "daresn't": "dare not",
     "didn't": "did not",
     "doesn't": "does not",
     "don't": "do not",
     "d'ye": "do you",
     "e'er": "ever",
     "everybody's": "everybody is",
     "everyone's": "everyone is",
     "finna": "going to",
     "g'day": "good day",
     "gimme": "give me",
     "giv'n": "given",
     "gonna": "going to",
     "gotta": "got to",
     "hadn't": "had not",
     "had've": "had have",
     "hasn't": "has not",
     "haven't": "have not",
     "havnt": "have not",
     "havent": "have not",
     "he'd": "he had",
     "he's": "he is",
     "he've": "he have",
     "how'd": "how did",
     "howdy": "how do you do",
     "how'll": "how shall",
     "how're": "how are",
     "how's": "how has",
     "i'd": "i had",
     "i'd've": "i would have",
     "i'll": "i will",
     "i've": "i have",
     "i'd've": "i would have",
     "i'm": "i am",
     "i'm'a": "i am about to",
     "i'm'o": "i am going to",
     "innit": "is it not",
     "i've": "i have",
     "isn't": "is not",
     "it'd": "it would",
     "it'll": "it will",
     "it's": "it is",
     "let's": "let us",
     "ma'am": "madam",
     "mayn't": "may not",
     "may've": "may have",
     "methinks": "me thinks",
     "mightn't": "might not",
     "might've": "might have",
     "mustn't": "must not",
     "mustn't've": "must not have",
     "must've": "must have",
     "needn't": "need not",
     "ne'er": "never",
     "o'clock": "of the clock",
     "o'er": "over",
     "ol'": "old",
     "oughtn't": "ought not",
     "shalln't": "shall not",
     "shan't": "shall not",
     "she'd": "she had",
     "she'll": "she will",
     "she's": "she is",
     "should've": "should have",
     "shouldn't": "should not",
     "shouldn't've": "should not have",
     "somebody's": "somebody has",
     "someone's": "someone has",
     "something's": "something has",
     "so're": "so are",
     "that'll": "that shall",
     "that're": "that are",
     "that'd": "that would",
     "there'd": "there had",
     "there'll": "there shall",
     "there're": "there are",
     "there's": "there has",
     "these're": "these are",
     "these've": "these have",
     "they'd": "they had",
     "they'll": "they will",
     "they're": "they are",
     "they've": "they have",
     "this's": "this has",
     "those're": "those are",
     "those've": "those have",
     "'tis": "it is",
     "to've": "to have",
     "'twas": "it was",
     "wanna": "want to",
     "wasn't": "was not",
     "we'd": "we had",
     "we'd've": "we would have",
     "we'll": "we will",
     "we're": "we are",
     "we've": "we have",
     "weren't": "were not",
     "what'd": "what did",
     "what'll": "what shall",
     "what're": "what are",
     "what's": "what has",
     "what've": "what have",
     "when's": "when has",
     "where'd": "where did",
     "where'll": "where shall",
     "where're": "where are",
     "where's": "where has",
     "where've": "where have",
     "which'd": "which had",
     "which'll": "which shall",
     "which're": "which are",
     "which's": "which has",
     "which've": "which have",
     "who'd": "who would",
     "who'd've": "who would have",
     "who'll": "who shall",
     "who're": "who are",
     "who've": "who have",
     "why'd": "why did",
     "why're": "why are",
     "why's": "why has",
     "won't": "will not",
     "would've": "would have",
     "wouldn't": "would not",
     "wouldn't've": "would not have",
     "y'all": "you all",
     "y'all'd've": "you all would have",
     "y'all're": "you all are",
     "you'd": "you had",
     "you'll": "you will",
     "you're": "you are",
     "u're": "you are",
     "you've": "you have",
     "u": "you",
     "aight": "alright",
     "aint": "are not",
     "amnt": "am not",
     "arent": "are not",
     "cant": "can not",
     "couldve": "could have",
     "couldnt": "could not",
     "couldntve": "could not have",
     "darent": "dare not",
     "daresnt": "dare not",
     "dasnt": "dare not",
     "didnt": "did not",
     "doesnt": "does not",
     "dont": "do not",
     "eer": "ever",
     "everybodys": "everybody is",
     "everyones": "everyone is",
     "finna": "fixing to",
     "gday": "good day",
     "gimme": "give me",
     "givn": "given",
     "gonna": "going to",
     "gonn": "going to",
     "goin'": "going",
     "gotta": "got to",
     "hadnt": "had not",
     "hadve": "had have",
     "hasnt": "has not",
     "havent": "have not",
     "hed": "he had",
     "he'll": "he will",
     "hes": "he has",
     "heve": "he have",
     "howd": "how did",
     "howdy": "how do you do",
     "howll": "how will",
     "howre": "how are",
     "hows": "how has",
     "idve": "i would have",
     "ill": "i will",
     "im": "i am",
     "ima": "i am about to",
     "ive": "i have",
     "isnt": "is not",
     "itd": "it would",
     "itll": "it shall",
     "its": "it is",
     "lets": "let us",
     "maam": "madam",
     "maynt": "may not",
     "mayve": "may have",
     "methinks": "me thinks",
     "mightnt": "might not",
     "mightve": "might have",
     "mustnt": "must not",
     "mustntve": "must not have",
     "mustve": "must have",
     "neednt": "need not",
     "neer": "never",
     "oclock": "of the clock",
     "oer": "over",
     "ol": "old",
     "oughtnt": "ought not",
     "shallnt": "shall not",
     "shant": "shall not",
     "shed": "she had",
     "shell": "she will",
     "shes": "she has",
     "shouldve": "should have",
     "shouldnt": "should not",
     "shouldntve": "should not have",
     "somebodys": "somebody has",
     "someones": "someone has",
     "somethings": "something has",
     "thatll": "that shall",
     "thatre": "that are",
     "thatd": "that would",
     "thered": "there had",
     "therell": "there shall",
     "therere": "there are",
     "theres": "there has",
     "thesere": "these are",
     "theseve": "these have",
     "theyd": "they had",
     "theyll": "they shall",
     "theyre": "they are",
     "theyve": "they have",
     "thosere": "those are",
     "thoseve": "those have",
     "tis": "it is",
     "tove": "to have",
     "twas": "it was",
     "wanna": "want to",
     "wasnt": "was not",
     "wed": "we had",
     "wedve": "we would have",
     "weve": "we have",
     "werent": "were not",
     "whatd": "what did",
     "whatll": "what shall",
     "whatre": "what are",
     "whats": "what has",
     "whatve": "what have",
     "whens": "when has",
     "whered": "where did",
     "wherell": "where shall",
     "wherere": "where are",
     "wheres": "where has",
     "whereve": "where have",
     "whichd": "which had",
     "whichll": "which shall",
     "whichre": "which are",
     "whichs": "which has",
     "whichve": "which have",
     "whod": "who would",
     "whodve": "who would have",
     "wholl": "who shall",
     "whore": "who are",
     "whos": "who has",
     "whove": "who have",
     "whyd": "why did",
     "whyre": "why are",
     "whys": "why has",
     "wont": "will not",
     "wouldve": "would have",
     "wouldnt": "would not",
     "wouldntve": "would not have",
     "yall": "you all",
     "yalldve": "you all would have",
     "yallre": "you all are",
     "youd": "you had",
     "youll": "you shall",
     "youre": "you are",
     "yr": "youre",
     "ur": "youre",
     "youve": "you have",
     "'re": "are",
     "that's": "that is",
     "thats": "that is",
     "ion": "i do not",
     "i'on": "i do not",
     "lemme": "let me",
     "outta": "out of",
     "kinda": "kind of",
     "sorta": "sort of",
     "lotta": "lot of",
     "cuzza": "because of",
     "prolly": "probably",
     "imma": "i am going to",
     "brb": "be right back",
     "bbl": "be back later",
     "b4": "before",
     "bc": "because",
     "bcoz": "because",
     "idk": "i dont know",
     "ikr": "i know right",
     "rn": "right now",
     "smh": "shaking my head",
     "wtf": "what the fuck",
     "tf": "the fuck",
     "lmk": "let me know",
     "nvm": "never mind",
     "ppl": "people",
     "yall": "you all",
     "ya": "you",
     "u": "you",
     "r": "are",
     "ur": "you are",
     "rite": "right",
     "dnt": "do not",
     "pls": "please",
     "plz": "please",
     "tho": "though",
     "bcuz": "because",
     "cuz": "because",
     "sup": "what is up",
     "ftw": "for the win",
     "omg": "oh my god",
     "gg": "good game",
     "gn": "good night",
     "gr8": "great",
     "hmu": "hit me up",
     "omw": "on my way",
     "yolo": "you only live once",
     "nah": "no",
     "yup": "yes",
     "yep": "yes",
     "naw": "no",
     "ok": "okay",
     "fr": "for real",
     "dm": "direct message",
     "fam": "close friend",
     "deadass": "seriously",
     "tho": "though",
     "thx": "thanks",
     "thnks": "thanks",
     "thnks": "thanks",
     "thnx": "thanks",
     "ty": "thank you",
     "np": "no problem",
     "lol": "laughing out loud",
     "lmao": "laughing my ass off",
     "rofl": "rolling on the floor laughing",
     "tbh": "to be honest",
     "atm": "at the moment",
     "btw": "by the way",
     "idc": "i do not care",
     "ily": "i love you",
     "ilysm": "i love you so much",
     "imho": "in my humble opinion",
     "imo": "in my opinion",
     "jk": "just kidding",
     "ttyl": "talk to you later",
     "bff": "best friends forever",
     "wyd": "what are you doing",
     "wbu": "what about you",
     "hbu": "how about you",
     "bruh": "brother",
     "bro": "brother",
     "sis": "sister",
     "cu": "see you",
     "cya": "see you",
     "gtg": "got to go",
     "g2g": "got to go",
     "2c": "to see",
     "sez": "says",
     "nope": "no",
     "hecka": "very",
     "hella": "very",
     "obvi": "obviously",
     "tryna": "trying to",
     "wassup": "what is up",
     "whatchu": "what are you",
     "chu": "you",
     "nahh": "no",
     "yaaa": "yes",
     "vibe": "feeling",
     "woulda": "would have",
     "mighta": "might have",
     "hafta": "have to",
     "needa": "need to",
     "coulda": "could have",
     "shoulda": "should have",
     "ya'll": "you all",
     "yall": "you all",
     "dat": "that",
     "dis": "this",
     "dere": "there",
     "doin": "doing",
     "nuthin": "nothing",
     "alotta": "a lot of",
     "kewl": "cool",
     "omfg": "oh my fucking god",
     "lmao": "laughing my ass off",
     "ily": "i love you",
     "nite": "night",
     "nitey": "nighty",
     "bday": "birthday",
     "l8r": "later",
     "2day": "today",
     "tday": "today",
     "2moro": "tomorrow",
     "2mrw": "tomorrow",
     "4eva": "forever",
     "hun": "honey",
     "dunno": "dont know",
     "nt": "not",
     "chillen": "chilling",
     "chillin": "chilling",
     "fuckin": "fucking",
     "temp": "temperature",
     "congrats": "congratulation",
     "ight": "allright",
     "c": "see",
     "h8": "hate",
     "m8": "mate",
     "sk8": "skate",
     "sk8r": "skater",
     "d8": "date",
     "w8": "wait",
     "r8": "rate",
     "2moro": "tomorrow",
     "2nite": "tonight",
     "4get": "forget",
     "4got": "forgot",
     "4u": "for you",
     "fella": "fellow",
     "fyi": "for your info",
     "smh": "shaking my head",
     "str8": "straight",
     "who's": "who is"
     }

HTML_DICT = {
    "&amp;": "&",
    "&lt;": "<",
    "&gt;": ">",
    "&quot;": "\"",
    "&apos;": "'",
    "&nbsp;": " ",
    "&copy;": "©",
    "&reg;": "®",
    "&trade;": "™",
    "&mdash;": "—",
    "&ndash;": "–",
    "&hellip;": "…",
    "&iexcl;": "¡",
    "&iquest;": "¿",
    "&deg;": "°"
}

ASCII_EMOJI_TO_TOKEN = {
    ":)": "[HAPPY]",
    ":-)": "[HAPPY]",
    ":D": "[VERY_HAPPY]",
    ":-D": "[VERY_HAPPY]",
    ":(": "[SAD]",
    ":-(": "[SAD]",
    ":|": "[NEUTRAL]",
    ":-|": "[NEUTRAL]",
    ":/": "[UNSURE]",
    ":-/": "[UNSURE]",
    ":\\": "[UNSURE]",
    ":-\\": "[UNSURE]",
    ":P": "[PLAYFUL]",
    ":-P": "[PLAYFUL]",
    ";)": "[WINK]",
    ";-)": "[WINK]",
    ":o": "[SURPRISED]",
    ":-o": "[SURPRISED]",
    ":O": "[SURPRISED]",
    ":-O": "[SURPRISED]",
    ":'(": "[CRYING]",
    ":'-)": "[HAPPY_TEARS]",
    ":')": "[HAPPY_TEARS]",
    "<3": "[LOVE]",
    "</3": "[HEARTBROKEN]",
    ":*": "[KISS]",
    ":-*": "[KISS]",
    "XD": "[LAUGHING]",
    "xD": "[LAUGHING]",
    "XP": "[LAUGHING]",
    ">:(": "[ANGRY]",
    "D:": "[HORRIFIED]",
    ":3": "[CUTE]",
    "O:)": "[INNOCENT]",
    ">:O": "[SHOCKED]",
    "T_T": "[CRYING]",
    "-_-": "[ANNOYED]",
    "^_^": "[HAPPY]",
    "O_O": "[SHOCKED]",
    "-.-": "[DISAPPOINTED]",
    "=_=": "[TIRED]",
    "UwU": "[CUTE]",
    "OwO": "[SURPRISED_CUTE]",
}

STOP_WORDS = (
"kinda", "'ll", "'tis", "'twas", "'ve", "10", "39", "a", "a's", "able", "ableabout", "about", "above", "abroad", "abst",
"accordance", "according", "accordingly", "across", "act", "actually", "ad", "added", "adj", "adopted", "ae", "af",
"affected", "affecting", "affects", "after", "afterwards", "ag", "again", "against", "ago", "ah", "ahead", "ai",
"ain't", "aint", "al", "all", "allow", "allows", "almost", "alone", "along", "alongside", "already", "also", "although",
"always", "am", "amid", "amidst", "among", "amongst", "amoungst", "amount", "an", "and", "announce", "another", "any",
"anybody", "anyhow", "anymore", "anyone", "anything", "anyway", "anyways", "anywhere", "ao", "apart", "apparently",
"appear", "appreciate", "appropriate", "approximately", "aq", "ar", "are", "area", "areas", "aren", "aren't", "arent",
"arise", "around", "arpa", "as", "aside", "ask", "asked", "asking", "asks", "associated", "at", "au", "auth",
"available", "aw", "away", "awfully", "az", "b", "ba", "back", "backed", "backing", "backs", "backward", "backwards",
"bb", "bd", "be", "became", "because", "become", "becomes", "becoming", "been", "before", "beforehand", "began",
"begin", "beginning", "beginnings", "begins", "behind", "being", "beings", "believe", "below", "beside", "besides",
"best", "better", "between", "beyond", "bf", "bg", "bh", "bi", "big", "bill", "billion", "biol", "bj", "bm", "bn", "bo",
"both", "bottom", "br", "brief", "briefly", "bs", "bt", "but", "buy", "bv", "bw", "by", "bz", "c", "c'mon", "c's", "ca",
"call", "came", "can", "can't", "cannot", "cant", "caption", "case", "cases", "cause", "causes", "cc", "cd", "certain",
"certainly", "cf", "cg", "ch", "changes", "ci", "ck", "cl", "clear", "clearly", "click", "cm", "cmon", "cn", "co",
"co.", "com", "come", "comes", "computer", "con", "concerning", "consequently", "consider", "considering", "contain",
"containing", "contains", "copy", "corresponding", "could", "could've", "couldn", "couldn't", "couldnt", "course", "cr",
"cry", "cs", "cu", "currently", "cv", "cx", "cy", "cz", "d", "dare", "daren't", "darent", "date", "de", "dear",
"definitely", "describe", "described", "despite", "detail", "did", "didn", "didn't", "didnt", "differ", "different",
"differently", "directly", "dj", "dk", "dm", "do", "does", "doesn", "doesn't", "doesnt", "doing", "don", "don't",
"done", "dont", "doubtful", "down", "downed", "downing", "downs", "downwards", "due", "during", "dz", "e", "each",
"early", "ec", "ed", "edu", "ee", "effect", "eg", "eh", "eight", "eighty", "either", "eleven", "else", "elsewhere",
"empty", "end", "ended", "ending", "ends", "enough", "entirely", "er", "es", "especially", "et", "et-al", "etc", "even",
"evenly", "ever", "evermore", "every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example",
"except", "f", "face", "faces", "fact", "facts", "fairly", "far", "farther", "felt", "few", "fewer", "ff", "fi",
"fifteen", "fifth", "fifty", "fify", "fill", "find", "finds", "fire", "first", "five", "fix", "fj", "fk", "fm", "fo",
"followed", "following", "follows", "for", "forever", "former", "formerly", "forth", "forty", "forward", "found",
"four", "fr", "free", "from", "front", "full", "fully", "further", "furthered", "furthering", "furthermore", "furthers",
"fx", "g", "ga", "gave", "gb", "gd", "ge", "general", "generally", "get", "gets", "getting", "gf", "gg", "gh", "gi",
"give", "given", "gives", "giving", "gl", "gm", "gmt", "gn", "go", "goes", "going", "gone", "good", "goods", "got",
"gotten", "gov", "gp", "gq", "gr", "great", "greater", "greatest", "greetings", "group", "grouped", "grouping",
"groups", "gs", "gt", "gu", "gw", "gy", "h", "had", "hadn't", "hadnt", "half", "happens", "hardly", "has", "hasn",
"hasn't", "hasnt", "have", "haven", "haven't", "havent", "having", "he", "he'd", "he'll", "he's", "hed", "hell",
"hello", "help", "hence", "her", "here", "here's", "hereafter", "hereby", "herein", "heres", "hereupon", "hers",
"herself", "herse”", "hes", "hi", "hid", "high", "higher", "highest", "him", "himself", "himse”", "his", "hither", "hk",
"hm", "hn", "home", "homepage", "hopefully", "how", "how'd", "how'll", "how's", "howbeit", "however", "hr", "ht", "htm",
"html", "http", "hu", "hundred", "i", "i'd", "i'll", "i'm", "i've", "i.e.", "id", "ie", "if", "ignored", "ii", "il",
"ill", "im", "immediate", "immediately", "importance", "important", "in", "inasmuch", "inc", "inc.", "indeed", "index",
"indicate", "indicated", "indicates", "information", "inner", "inside", "insofar", "instead", "int", "interest",
"interested", "interesting", "interests", "into", "invention", "inward", "io", "iq", "ir", "is", "isn", "isn't", "isnt",
"it", "it'd", "it'll", "it's", "itd", "itll", "its", "itself", "itse”", "ive", "j", "je", "jm", "jo", "join", "jp",
"just", "k", "ke", "keep", "keeps", "kept", "keys", "kg", "kh", "ki", "kind", "km", "kn", "knew", "know", "known",
"knows", "kp", "kr", "kw", "ky", "kz", "l", "la", "large", "largely", "last", "lately", "later", "latest", "latter",
"latterly", "lb", "lc", "least", "length", "less", "lest", "let", "let's", "lets", "li", "like", "liked", "likely",
"likewise", "line", "little", "lk", "ll", "long", "longer", "longest", "look", "looking", "looks", "low", "lower", "lr",
"ls", "lt", "ltd", "lu", "lv", "ly", "m", "ma", "made", "mainly", "make", "makes", "making", "man", "many", "may",
"maybe", "mayn't", "maynt", "mc", "md", "me", "mean", "means", "meantime", "meanwhile", "member", "members", "men",
"merely", "mg", "mh", "microsoft", "might", "might've", "mightn't", "mightnt", "mil", "mill", "million", "mine",
"minus", "miss", "mk", "ml", "mm", "mn", "mo", "more", "moreover", "most", "mostly", "move", "mp", "mq", "mr", "mrs",
"ms", "msie", "mt", "mu", "much", "mug", "must", "must've", "mustn't", "mustnt", "mv", "mw", "mx", "my", "myself",
"myse”", "mz", "n", "na", "name", "namely", "nay", "nc", "nd", "ne", "near", "nearly", "necessarily", "necessary",
"need", "needed", "needing", "needn't", "neednt", "needs", "neither", "net", "netscape", "never", "neverf", "neverless",
"nevertheless", "new", "newer", "newest", "next", "nf", "ng", "ni", "nine", "ninety", "nl", "no", "no-one", "nobody",
"non", "none", "nonetheless", "noone", "nor", "normally", "nos", "not", "noted", "nothing", "notwithstanding", "novel",
"now", "nowhere", "np", "nr", "nu", "null", "number", "numbers", "nz", "o", "obtain", "obtained", "obviously", "of",
"off", "often", "oh", "ok", "okay", "old", "older", "oldest", "om", "omitted", "on", "once", "one", "one's", "ones",
"only", "onto", "open", "opened", "opening", "opens", "opposite", "or", "ord", "order", "ordered", "ordering", "orders",
"org", "other", "others", "otherwise", "ought", "oughtn't", "oughtnt", "our", "ours", "ourselves", "out", "outside",
"over", "overall", "owing", "own", "p", "pa", "page", "pages", "part", "parted", "particular", "particularly",
"parting", "parts", "past", "pe", "per", "perhaps", "pf", "pg", "ph", "pk", "pl", "place", "placed", "places", "please",
"plus", "pm", "pmid", "pn", "point", "pointed", "pointing", "points", "poorly", "possible", "possibly", "potentially",
"pp", "pr", "predominantly", "present", "presented", "presenting", "presents", "presumably", "previously", "primarily",
"probably", "problem", "problems", "promptly", "proud", "provided", "provides", "pt", "put", "puts", "pw", "py", "q",
"qa", "que", "quickly", "quite", "qv", "r", "ran", "rather", "rd", "re", "readily", "really", "reasonably", "recent",
"recently", "ref", "refs", "regarding", "regardless", "regards", "related", "relatively", "research", "reserved",
"respectively", "resulted", "resulting", "results", "right", "ring", "ro", "room", "rooms", "round", "ru", "run", "rw",
"s", "sa", "said", "same", "saw", "say", "saying", "says", "sb", "sc", "sd", "se", "sec", "second", "secondly",
"seconds", "section", "see", "seeing", "seem", "seemed", "seeming", "seems", "seen", "sees", "self", "selves",
"sensible", "sent", "serious", "seriously", "seven", "seventy", "several", "sg", "sh", "shall", "shan't", "shant",
"she", "she'd", "she'll", "she's", "shed", "shell", "shes", "should", "should've", "shouldn", "shouldn't", "shouldnt",
"show", "showed", "showing", "shown", "showns", "shows", "si", "side", "sides", "significant", "significantly",
"similar", "similarly", "since", "sincere", "site", "six", "sixty", "sj", "sk", "sl", "slightly", "sm", "small",
"smaller", "smallest", "sn", "so", "some", "somebody", "someday", "somehow", "someone", "somethan", "something",
"sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "specifically", "specified", "specify", "specifying",
"sr", "st", "state", "states", "still", "stop", "strongly", "su", "sub", "substantially", "successfully", "such",
"sufficiently", "suggest", "sup", "sure", "sv", "sy", "system", "sz", "t", "t's", "take", "taken", "taking", "tc", "td",
"tell", "ten", "tends", "test", "text", "tf", "tg", "th", "than", "thank", "thanks", "thanx", "that", "that'll",
"that's", "that've", "thatll", "thats", "thatve", "the", "their", "theirs", "them", "themselves", "then", "thence",
"there", "there'd", "there'll", "there're", "there's", "there've", "thereafter", "thereby", "thered", "therefore",
"therein", "therell", "thereof", "therere", "theres", "thereto", "thereupon", "thereve", "these", "they", "they'd",
"they'll", "they're", "they've", "theyd", "theyll", "theyre", "theyve", "thick", "thin", "thing", "things", "think",
"thinks", "third", "thirty", "this", "thorough", "thoroughly", "those", "thou", "though", "thoughh", "thought",
"thoughts", "thousand", "three", "throug", "through", "throughout", "thru", "thus", "til", "till", "tip", "tis", "tj",
"tk", "tm", "tn", "to", "today", "together", "too", "took", "top", "toward", "towards", "tp", "tr", "tried", "tries",
"trillion", "truly", "try", "trying", "ts", "tt", "turn", "turned", "turning", "turns", "tv", "tw", "twas", "twelve",
"twenty", "twice", "two", "tz", "u", "ua", "ug", "uk", "um", "un", "under", "underneath", "undoing", "unfortunately",
"unless", "unlike", "unlikely", "until", "unto", "up", "upon", "ups", "upwards", "us", "use", "used", "useful",
"usefully", "usefulness", "uses", "using", "usually", "uucp", "uy", "uz", "v", "va", "value", "various", "vc", "ve",
"versus", "very", "vg", "vi", "via", "viz", "vn", "vol", "vols", "vs", "vu", "w", "want", "wanted", "wanting", "wants",
"was", "wasn", "wasn't", "wasnt", "way", "ways", "we", "we'd", "we'll", "we're", "we've", "web", "webpage", "website",
"wed", "welcome", "well", "wells", "went", "were", "weren", "weren't", "werent", "weve", "wf", "what", "what'd",
"what'll", "what's", "what've", "whatever", "whatll", "whats", "whatve", "when", "when'd", "when'll", "when's",
"whence", "whenever", "where", "where'd", "where'll", "where's", "whereafter", "whereas", "whereby", "wherein",
"wheres", "whereupon", "wherever", "whether", "which", "whichever", "while", "whilst", "whim", "whither", "who",
"who'd", "who'll", "who's", "whod", "whoever", "whole", "wholl", "whom", "whomever", "whos", "whose", "why", "why'd",
"why'll", "why's", "widely", "width", "will", "willing", "wish", "with", "within", "without", "won", "won't", "wonder",
"wont", "words", "work", "worked", "working", "works", "world", "would", "would've", "wouldn", "wouldn't", "wouldnt",
"ws", "www", "x", "y", "ye", "year", "years", "yes", "yet", "you", "you'd", "you'll", "you're", "you've", "youd",
"youll", "young", "younger", "youngest", "your", "youre", "yours", "yourself", "yourselves", "youve", "yt", "yu", "z",
"za", "zero", "zm", "zr", "hey")

# regex for detecting any type of url
URL_RE = r'(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})'
# url token
URL_TOKEN = "[URL]"

# regex for detecting usernames
USER_RE = r'@\w+'
# user token
USER_TOKEN = "[USER]"

# regex for detecting hashtag
HASHTAG_RE = r'#\S+'
# hashtag token
HASHTAG_TOKEN = "[HASHTAG]"

# marker for beginning of a word
BEGINNING_OF_WORD_MARK = "<W>"

# spliting text strings to pre tokens predefined regex
SPLITER_REGEX = r"""(@\w+|#\w+|https?://\S+|\d+|[^\w\s]|[\w']+|\s+)"""
